# Generated by Django 5.1.3 on 2025-02-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(default='userprofile/avatar.svg', null=True, upload_to='userprofile'),
        ),
    ]
