# Generated by Django 5.1.3 on 2025-02-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_alter_customuser_name_alter_customuser_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommessage', to='chatroom.room'),
        ),
    ]
